config/routes.rb
Rails.application.routes.draw do
  get 'info/about'
  get 'info/news'

  devise_for :users
  get 'user/view_profile'
  get 'user/get_email'
  
  resources :exercise_type, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :workout, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :exercise, only: [:new, :create, :edit, :update, :destroy]
  resources :post, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "user#view_profile"
end 

app/controllers/exercise_type_controller.rb
class ExerciseTypeController < ApplicationController
    before_action :authenticate_user!

    # просмотреть все упражнения данного юзера
    def index
        @exercise_types = ExerciseType.where(user_id: current_user.id)
        
        # все упражнения, используемые в тренировках
        @exercise_types_used = ExerciseType.where(id: Exercise.pluck(:exercise_type_id).flatten.uniq, user_id: current_user.id)
    end

    # создание нового типа упражнений
    def new
    end

    def create
        @exercise = ExerciseType.new(name: params[:name], description: params[:description], user_id: current_user.id)
        if @exercise.save
            redirect_to exercise_type_index_path, notice: 'Упражнение успешно добавлено!'
        else
            render :new
        end
    end

    # изменение упражнения по данному id
    def edit
        @exercise = ExerciseType.find(params[:id])
    end

    def update
        @exercise = ExerciseType.find(params[:id])
        if @exercise.update(name: params[:exercise_type][:name], description: params[:exercise_type][:description])
            redirect_to exercise_type_index_path
        else
            render :edit
        end
    end

    # удаление упражнения
    def destroy
        @exercise = ExerciseType.find(params[:id])
        @exercise.destroy
        redirect_to exercise_type_index_path
    end
end

app/helpers/exercise_type_helper.rb
module ExerciseTypeHelper
end

app/views/exercise_type/edit.html.erb
<h1>Изменить упражнение</h1>

<div class="col-lg-4 col-12 mb-4">
  <div class="my_form">
    <%= form_for @exercise, url: exercise_type_path(@exercise), method: :patch, class: "my_form", id: "my_form" do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control", placeholder: "Название" %>
        <%= f.text_field :description, class: "form-control", placeholder: "Описание" %>
      </div>
      <%= f.submit 'Сохранить', id: "submit_button", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/exercise_type/index.html.erb
<h1>Мои упражнения</h1>

<div class="col-lg-4 col-12 mb-4">
  <ul>
    <% @exercise_types.each do |exercise| %>
      <li>
      <div class="my_form">
        <div class="my_textbox">
          <div><b><%= exercise.name %></b></div>
          <div><%= exercise.description %></div>
        </div>

        <div class="btn-group">
          <%= button_to 'Изменить', edit_exercise_type_path(exercise), method: :get, class: "btn btn-primary my_horizontal_btn_group" %>
          <%= button_to 'Удалить', exercise_type_path(exercise), method: :delete, class: "btn btn-danger my_horizontal_btn_group",
            id: exercise.id %>
        </div>
      </div>
      </li>
    <% end %>
  </ul>
</div>

<script>
  // все упражнения, используемые в тренировках
  var exerciseTypesUsed = JSON.parse('<%= raw @exercise_types_used.to_json %>');
  
  // id всех упражнений, используемых в тренировках
  var exerciseTypeIdsUsed = exerciseTypesUsed.map(function(item) {
    return item.id;
  });

  // убираем кнопки удаления у всех упражнений, используемых в тренировках
  exerciseTypeIdsUsed.forEach(id => {
    document.getElementById(id).style.display = "none";
  });
  
</script>

app/views/exercise_type/new.html.erb
<h1>Новое упражнение</h1>

<div class="col-lg-4 col-12 mb-4">
    <%= form_tag(exercise_type_index_path, {method: "post", class: "my_form", id: "my_form"}) do %>
        <div class="form-group">
            <%= text_field_tag (:name),"", class: "form-control", placeholder: "Название" %>
            <%= text_field_tag (:description),"", class: "form-control", placeholder: "Описание" %>
        </div>
        <%= submit_tag('Сохранить',  id: "submit_button", class: "btn btn-primary") %>
    <% end %>
</div>