config/routes.rb
Rails.application.routes.draw do
  get 'info/about'
  get 'info/news'

  devise_for :users
  get 'user/view_profile'
  get 'user/get_email'
  
  resources :exercise_type, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :workout, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :exercise, only: [:new, :create, :edit, :update, :destroy]
  resources :post, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "user#view_profile"
end 

app/models/exercise.rb
class Exercise < ApplicationRecord
    belongs_to :exercise_type
    belongs_to :workout
end

app/models/exercise_type.rb
class ExerciseType < ApplicationRecord
    belongs_to :user
    has_many :exercises
    validates_presence_of(:name)
end

app/controllers/exercise_controller.rb
class ExerciseController < ApplicationController
    before_action :authenticate_user!

    def new
    end

    # создание нового сделанного упражнения
    def create
        @exercise = Exercise.new(exercise_type_id: params[:exercise_type_id],
                                 comments: params[:comments],
                                 sets: params[:sets],
                                 workout_id: session[:current_workout_id])
        @exercise.save
    end

    # изменение упражнения по данному id
    def edit
        @exercise = Exercise.find(params[:id])
        @exercise_types = ExerciseType.where(user_id: current_user.id).pluck(:name, :id, :description)

        # добавление к названию упражнения описания (при наличии)
        @exercise_types = @exercise_types.map { |arr|
            if arr[2].empty?
                [arr[0].to_s, arr[1]]
            else
                ["#{arr[0]} (#{arr[2]})", arr[1]]
            end
        }
    end

    def update
        @exercise = Exercise.find(params[:id])
        @exercise.update(exercise_type_id: params[:exercise][:exercise_type_id],
                         comments: params[:exercise][:comments],
                         sets: params[:sets])
    end

    # удаление упражнения
    def destroy
        @exercise = Exercise.find(params[:id])
        @exercise.destroy
    end
end

app/helpers/exercise_helper.rb
module ExerciseHelper
end

app/views/exercise/edit.html.erb
<div id="update-exercise">
    <h3>Редактирование упражнения</h3>
    <div class="my_form">
        <%= form_for @exercise, url: exercise_path(@exercise), method: :patch do |form| %>
            <div class="form-group">
                <%= form.label :exercise_type_id, 'Тип упражнения' %>
                <%= form.select :exercise_type_id, @exercise_types, {}, { class: 'form-control' } %>
            </div>

            <div id="update-sets-container"></div>

            <%= link_to 'Добавить подход', '#', id: 'update-add-set-btn', class: 'btn btn-primary' %>
            <%= link_to 'Удалить', '#', id: 'update-remove-last-set-btn', class: 'btn btn-danger' %>

            <div class="form-group">
                <%= form.label :comments, 'Комментарии' %>
                <%= form.text_area :comments, class: 'form-control', rows: 3 %>
            </div>

            <%= form.submit 'Сохранить', id: "update-submit_button", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

<script id="update-sets-control-script">
    console.log("update-sets-control-script loaded")

    var updateSetCount = 0;
    var updateSetsContainer = document.getElementById('update-sets-container');
    var updateAddSetBtn = document.getElementById('update-add-set-btn');
    var updateRemoveLastSetBtn = document.getElementById('update-remove-last-set-btn');
    updateSetCount = 0;

    updateAddSetBtn.addEventListener('click', function(event) {
      event.preventDefault();
      var updateNewSetForm = document.createElement('div');
      updateNewSetForm.innerHTML = `
        <div class="form-group set-group">
          <label for="_sets_${updateSetCount}_weight">Вес</label>
          <input class="form-control" type="text" name="sets[${updateSetCount}][weight]">

          <label for="_sets_${updateSetCount}_reps">Количество повторений</label>
          <input class="form-control" type="text" name="sets[${updateSetCount}][reps]">
        </div>
      `;

      updateSetsContainer.appendChild(updateNewSetForm);
      updateSetCount++;
    });

    updateRemoveLastSetBtn.addEventListener('click', function(event) {
      event.preventDefault();
      var updateLastSet = updateSetsContainer.lastElementChild;
      if (updateLastSet) {
        updateLastSet.remove();
        updateSetCount--;
      }
    });
</script>