config/routes.rb
Rails.application.routes.draw do
  get 'info/about'
  get 'info/news'

  devise_for :users
  get 'user/view_profile'
  get 'user/get_email'
  
  resources :exercise_type, only: [:new, :create, :index, :edit, :update, :destroy]
  resources :workout, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :exercise, only: [:new, :create, :edit, :update, :destroy]
  resources :post, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "user#view_profile"
end 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-primary">
  <div class="container">
    <%= link_to 'FitLog Pro', info_about_path, class: 'navbar-brand' %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item <%= 'active' if current_page?(root_path) %>">
          <%= link_to 'Моя страница', root_path, class: 'nav-link' %>
        </li>

        <%
=begin%>
 <li class="nav-item <%= 'active' if current_page?(info_news_path) %>">
          <%= link_to 'Новости', info_news_path, class: 'nav-link' %>
        </li> 
<%
=end%>
        
        <li class="nav-item <%= 'active' if current_page?(new_exercise_type_path) %>">
          <%= link_to 'Новое упражнение', new_exercise_type_path, class: 'nav-link' %>
        </li>
        
        <li class="nav-item <%= 'active' if current_page?(exercise_type_index_path) %>">
          <%= link_to 'Мои упражнения', exercise_type_index_path, class: 'nav-link' %>
        </li>

        <li class="nav-item <%= 'active' if current_page?(new_workout_path) %>">
          <%= link_to 'Новая тренировка', new_workout_path, class: 'nav-link' %>
        </li>
        
        <li class="nav-item <%= 'active' if current_page?(workout_index_path) %>">
          <%= link_to 'Мои тренировки', workout_index_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FitLog Pro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css', media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container-fluid">
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js' %>
  </body>
</html>